name: "Wire Pod Home Assistant Add-on"
description: "Home Assistant Add-on to run Wire Pod"
version: "0.1.0"
slug: "wire_pod"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386